/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.AuthentincationTab_operations;
import Classes.Info_DB_Operations;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        
       
    }

        ResultSet usr_RS;
        Info_DB_Operations  idbo=new Info_DB_Operations ();
        AuthentincationTab_operations usrOp=new    AuthentincationTab_operations();
        JFrame frm;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void check_conformation()
    {
          try {
              
              //Check the data is inserted
            if(!"".equals(txtUserName.getText()) &&!"".equals(txtUserPassword.getText()))
             {
              //Check if the user name and the password inserted are correct
          
                 if(usrOp.verify_user(txtUserName.getText(), txtUserPassword.getText()))
               //If they are correct then show the sent frame
                 {frm.setVisible(true);
                  this.setVisible(false);
                 }
                else
                {
                 //If not then show message to inform the user to ensure the data
                   lblIncorrect.setText("! Sorry check the password or the user name ^-^ !");
                    txtUserPassword.setText("");
                 }
            
             }
            
            //if data is not inseted show message
            else if ("".equals(txtUserName.getText()))
                  JOptionPane.showMessageDialog(null, "User name field is empty", "Validation Error", JOptionPane.INFORMATION_MESSAGE);
           else if ("".equals(txtUserPassword.getText()))
            JOptionPane.showMessageDialog(null, "User password field is empty", "Validation Error", JOptionPane.INFORMATION_MESSAGE);
        
          
          } catch (SQLException ex) {
            Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserName = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblIncorrect = new javax.swing.JLabel();
        txtUserPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authentication");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.setBackground(new java.awt.Color(192, 192, 192));
        txtUserName.setToolTipText("user Name");
        txtUserName.setFocusCycleRoot(true);
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 195, 190, 30));

        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/btnLofin.jpg"))); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 304, 107, 24));

        jButton3.setToolTipText("Exit");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/btnLoginClose.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 5, 20, 16));

        lblIncorrect.setForeground(new java.awt.Color(253, 6, 6));
        lblIncorrect.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(lblIncorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 140, 18));

        txtUserPassword.setBackground(new java.awt.Color(192, 192, 192));
        txtUserPassword.setToolTipText("Password");
        getContentPane().add(txtUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 190, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/LoginBGf.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
      check_conformation();     
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIncorrect;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
