/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;


import Classes.Info_DB_Operations;
import Classes.SubjectTab_operations;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Administrator
 */
public class frmSubjects extends javax.swing.JFrame {

    /**
     * Creates new form Subject_Frame
     */
    public frmSubjects() {
        initComponents();
         try {
             
           
            //When the form is opened ,the subject table's data is shown           
            sub_RS=subOp.show_subjects();
           //Call the method designated for counting the total of records ans set the total lablel with the result
            lblTotal1.setText(idbo.show_total(sub_RS));
            //The first result is first shown 
            show_data(idbo.RS_first(sub_RS));
            
           
        } catch (SQLException ex) {
           
        }
        
    }
    
      //Initializing the global vars and methods that are used through the program
        ResultSet sub_RS;
        String path;
        Info_DB_Operations  idbo=new Info_DB_Operations ();
        SubjectTab_operations subOp=new  SubjectTab_operations();
        int index=1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     //Method to show data once starting the app
      private void show_data(ResultSet rs)
      {
          //Bind the fields of the table with the frame components properly
        try {
             txtID.setText(rs.getString("Subject_ID"));
             txtName.setText(rs.getString("Subject_Name"));
             txtDesc.setText(rs.getString("Subject_Details"));
             txtInstructor.setText(rs.getString("Subject_instructor"));
             cmbSubType.setSelectedItem(rs.getString("Subject_type"));
             txtLevel.setText(rs.getString("Subject_Level"));
              lblPosition1.setText(String.valueOf(index));
               show_image();
         
        } catch (SQLException ex) {
           
        }
    
      }
      //End of show data method
    
    //Method to initialize thr form to get the new entry
      private void add_new() throws SQLException
      {      //Call the method designated for addin new reord
              subOp.add_new();
              //Then jump to the inserted row
              sub_RS= subOp.show_subjects();
              index=Integer.valueOf(idbo.show_total(sub_RS));
              lblTotal1.setText(String.valueOf(index));
               lblPic.setIcon(null);           
             show_data(idbo.RS_last(sub_RS));
           
      
      }//End add new method
      
       private void set_update()
      {
         try {
           
            //Bind the values of the components with the parameters of the update method
                      
              String[] textboxes=new String[5];
             
              textboxes[0]= txtName.getText();
              textboxes[1]=cmbSubType.getSelectedItem().toString();
              textboxes[2]=txtInstructor.getText();
              textboxes[3]=txtDesc.getText();
              textboxes[4]=txtLevel.getText();
              
            
              
                //Call the update method
            subOp.update_Subject(Integer.valueOf(txtID.getText()), textboxes, null);
            
          
           
           } catch (SQLException ex) {JOptionPane.showMessageDialog(null,ex);   
        }
      
      }//End of update method 
      
      
      //Method to update the data 
       /**
        * 
        */
       public void update_frame() 
      {
      try { 
             //When we update first we check if the result set to updated is either search or show data
              
              if("".equals(txtSearch.getText()))
                 { 
                      set_update();
                     sub_RS=subOp.show_subjects();
                //Call the method regresh to show the new updates in the form instantly
                    show_data( idbo.refresh_data(sub_RS,index)  );
                }
              else
              {      
                    set_update();
                    sub_RS= subOp.search_subject(txtSearch.getText());
                    //Call the method regresh to show the new updates in the form instantly
                    show_data( idbo.refresh_data(sub_RS,index)  );
              }
                             

        } catch (SQLException ex) { 
          
        }
      
      
      }//End of update data method
      
      
      //Method to update the pic if any
      private ImageIcon show_image() 
      {
         byte[] imageData;
         ImageIcon format = null;
        try {
            if(sub_RS.getBytes("Subject_pic")!=null)
            {
            imageData = sub_RS.getBytes("Subject_pic");
            format = new ImageIcon(imageData);
            lblPic.setIcon(ResizeImage(format,lblPic));
            }
            else
            { ImageIcon myImg = new  ImageIcon(getClass().getResource("/Pics/Default.png"));
               lblPic.setIcon( myImg);}
        } catch (SQLException ex) {
            
        }
       
        return format;
      
      }
      //End of update image method 
      
       //Method to allow the user to chhose an image to be saved in the database
      private void setImage()
      {
   //
       JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "png", "gif");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File SelectedFile = fileChooser.getSelectedFile();
           path = SelectedFile.getAbsolutePath();
            ImageIcon myImg = new ImageIcon(path);
            //Call resize image method to fit the chosen image with the label pic
            lblPic.setIcon((ResizeImage(myImg,lblPic)));
        }
       
   }//End of choosing pic method
     //Mtethod to resize sent image
   private ImageIcon ResizeImage(ImageIcon myimg,JLabel lbl)
    {
     //Fit the inserted picture with  the size of the label
        java.awt.Image Img=myimg.getImage();
        java.awt.Image newImg=Img.getScaledInstance(lbl.getWidth(), lbl.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newImg);
        
        return image;
       
    
    
    }//End of resize image
      
      
      
      //Method to delete a specific row in a record
      private void delete_row() throws SQLException, FileNotFoundException, IOException
      { 
         
         //Call the method designated for deleting rows 
               subOp.delete_subject(Integer.valueOf(txtID.getText()));
           //then jump to the nearest row     
               sub_RS=subOp.show_subjects();
               index=Integer.valueOf(idbo.show_total(sub_RS));
               lblTotal1.setText(String.valueOf(index));
                   if(sub_RS.next())
                show_data(idbo.RS_next(sub_RS));
               else
                { index=1;
                   show_data(idbo.RS_first(sub_RS));
               }
      
      
      }  //End of delete row method
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtInstructor = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextPane();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lblPosition1 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        cmbSubType = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        lblPic = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Subjects");
        setLocationByPlatform(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 230, 30));

        txtID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 120, -1));

        txtInstructor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 240, 30));

        txtLevel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 240, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Level :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 60, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("[Subjects]");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 5, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Name  :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 50, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Description:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Instructor :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Type:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 34, -1));

        txtDesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(txtDesc);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 230, 110));

        btnDelete.setToolTipText("Delete this row");
        btnDelete.setBorder(null);
        btnDelete.setContentAreaFilled(false);
        btnDelete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Delete.jpg"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 3, 20, 20));

        btnUpdate.setToolTipText("update this row");
        btnUpdate.setBorder(null);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setInheritsPopupMenu(true);
        btnUpdate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Save 1.jpg"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 3, 20, 20));

        btnInsert.setToolTipText("Add new row");
        btnInsert.setBorder(null);
        btnInsert.setContentAreaFilled(false);
        btnInsert.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/new.jpg"))); // NOI18N
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 3, 20, 20));

        btnLast.setToolTipText("Move lats");
        btnLast.setBorder(null);
        btnLast.setBorderPainted(false);
        btnLast.setContentAreaFilled(false);
        btnLast.setRequestFocusEnabled(false);
        btnLast.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Last.jpg"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 3, 20, 20));

        btnNext.setToolTipText("Move next");
        btnNext.setBorder(null);
        btnNext.setContentAreaFilled(false);
        btnNext.setPreferredSize(new java.awt.Dimension(39, 23));
        btnNext.setRequestFocusEnabled(false);
        btnNext.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/next.jpg"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 3, 20, 20));

        jLabel13.setText("}");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 4, 10, 20));
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel10.setText("of {");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 3, -1, 20));
        getContentPane().add(lblPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        btnFirst.setBackground(new java.awt.Color(204, 255, 51));
        btnFirst.setToolTipText("Move first");
        btnFirst.setBorder(null);
        btnFirst.setContentAreaFilled(false);
        btnFirst.setPreferredSize(new java.awt.Dimension(39, 23));
        btnFirst.setRequestFocusEnabled(false);
        btnFirst.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/First.jpg"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 20, 20));

        btnPrevious.setToolTipText("Move previous");
        btnPrevious.setBorder(null);
        btnPrevious.setContentAreaFilled(false);
        btnPrevious.setPreferredSize(new java.awt.Dimension(39, 23));
        btnPrevious.setRequestFocusEnabled(false);
        btnPrevious.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Previous.jpg"))); // NOI18N
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 3, 20, 20));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtSearch.setToolTipText("Search for a text or ID");
        txtSearch.setPreferredSize(new java.awt.Dimension(216, 22));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtSearchInputMethodTextChanged(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 160, 25));

        lblPosition1.setToolTipText("Current position");
        getContentPane().add(lblPosition1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 3, 30, 20));

        lblTotal1.setToolTipText("Total rows");
        getContentPane().add(lblTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 3, 40, 20));

        cmbSubType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Eductional", "Self Study", "General", "Private" }));
        getContentPane().add(cmbSubType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 240, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("ID :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Default.png"))); // NOI18N
        lblPic.setToolTipText("Double click to set an image");
        lblPic.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPicMouseClicked(evt);
            }
        });
        getContentPane().add(lblPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 450, 210));

        jButton1.setToolTipText("Exit");
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/x1.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 20, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Searchicon_1.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 3, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/bar6.jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 30));

        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/SubjectBG.jpg"))); // NOI18N
        getContentPane().add(lblBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     
        //Check if the row is not the first ,if it is then disable the user to delete it
        if(Integer.valueOf(txtID.getText())==1)
        {btnDelete.enable(false);}
        //if not then call the method delete row
        else
        {
            //Alert the users before deleting by poping up an option message
       int result = JOptionPane.showConfirmDialog(null, "Are you sure you wish to delete this row ?","Alert", JOptionPane.YES_NO_CANCEL_OPTION);
      if(result == JOptionPane.YES_OPTION) {
       try {
            try {
                delete_row();
                
            } catch (FileNotFoundException ex) {
               
            } catch (IOException ex) {
               
            }
        } catch (SQLException ex) {     
        }
     }
       
        } 


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      //Call the method designated for update
        update_frame();
        

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
     //call the method designated for adding row
        try {
            add_new();
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,ex);
        }
      
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        //Call update data to save changes made in the row
                 
        try {
             update_frame();
               index=Integer.valueOf(lblTotal1.getText());
            show_data(idbo.RS_last(sub_RS));
         
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
                  //Set the index to the last item in the record

    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed


              //Check if the index is not the last item 
          
            try {
                
                //Call update data to save changes made in the row
                 update_frame();
                   if(index<(Integer.valueOf(lblTotal1.getText())))
                     {   //if not then decrement the index to the next item in the record
                           index++;
                          //Show the data of the next record
                         show_data(idbo.RS_next(sub_RS));
                 }
                //show_image();
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,ex);
            }





    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed

try {
                 //Call update data to save changes made in the row
             update_frame();
        
                  if(index>1)
                  {
             //if not then decrement the index to the previous item in the record
                  index--;
                show_data(idbo.RS_previous(sub_RS));}
            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null,ex);
            }





    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed


   try {
               index = 1;
                //Call update data to save changes made in the row
               update_frame();
            //Show the data existing in the first item record
           show_data(idbo.RS_first(sub_RS));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
       





    }//GEN-LAST:event_btnFirstActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed

        // TODO add your handling code here:
   }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtSearchInputMethodTextChanged

   }//GEN-LAST:event_txtSearchInputMethodTextChanged

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyPressed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
 
            try {
                //check if the search text is empty then show the all data
                   if("".equals(txtSearch.getText()))
                    {  index=1;
                      sub_RS=subOp.show_subjects();
                      lblTotal1.setText(idbo.show_total(sub_RS));
               
                       show_data(idbo.RS_first(sub_RS));
                     }
                  else
                     {
                         //otherwise show the data according to the text enetered by the users
                      index=1;
                       sub_RS= subOp.search_subject(txtSearch.getText());
                       lblTotal1.setText(idbo.show_total(sub_RS));
                        show_data(idbo.RS_first(sub_RS));                               
                     }
            } catch (SQLException ex) {
               
            }




    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:

   }//GEN-LAST:event_txtSearchKeyTyped

    private void lblPicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPicMouseClicked
        //If user clicks the mouse twice then make him choose an image and insert it to the database
        if (evt.getClickCount() == 2) {
            try {
                setImage();
                subOp.sub_picUpdate(path, Integer.valueOf(txtID.getText()));
            } catch (FileNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }


    }//GEN-LAST:event_lblPicMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       JOptionPane.showMessageDialog(null, "Please do note forget to click the refresh button", "Remeber",JOptionPane.OK_OPTION);
    }//GEN-LAST:event_jButton1ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new frmSubjects().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbSubType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblPosition1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JTextPane txtDesc;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtInstructor;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
