/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Info_DB_Operations;
import Classes.PlansTab_operations;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class frmPlans extends javax.swing.JFrame {

    /**
     * Creates new form frmPlans
     * @throws SQLException 
     */
    public frmPlans() throws SQLException {
        initComponents();
         //To set the image of the frame
          this.setIconImage(new ImageIcon(getClass()
                    .getResource("/Pics/Icons/plns.gif")).getImage());
        
          //When the form is opened ,the subject table's data is shown           
               pln_RS=PlnOp.show_plans();
               //Call the method designated for counting the total of records ans set the total lablel with the result
                lblTotal1.setText(idbo.show_total(pln_RS));
                //The first result is first shown 
                 show_data(idbo.RS_first(pln_RS));
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
     //Initializing the global vars and methods that are used through the program
        ResultSet pln_RS;
        String path;
        Info_DB_Operations  idbo=new Info_DB_Operations ();
        PlansTab_operations PlnOp=new    PlansTab_operations();
        int index=1;

    
     //Method to show data once starting the app
      private void show_data(ResultSet rs)
      {
          //Bind the fields of the table with the frame components properly
        try {
            
             txtID.setText(rs.getString("pln_ID"));
             txtplan.setText(rs.getString("plan"));
             txtDetails.setText(rs.getString("Description"));
               lblPosition1.setText(String.valueOf(index));
            
            
           
        } catch (SQLException ex) {
           // Logger.getLogger(frmMainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    
      }
      //End of show data method
      
     
      
      
    //Method to initialize thr form to get the new entry
      private void add_new() throws SQLException
      
      {     
          //Call the method designated for addin new reord
               PlnOp.add_new();
              //Then jump to the inserted row
             pln_RS= PlnOp.show_plans();
              index=Integer.valueOf(idbo.show_total(pln_RS));
              lblTotal1.setText(String.valueOf(index));
                      
              show_data(idbo.RS_last(pln_RS));
          
      
      }//End add new method
      
       private void set_update()
      {
         try {
           
            //Bind the values of the components with the parameters of the update method
                      
              String[] textboxes=new String[2];
             
              textboxes[0]=  txtplan.getText();
              textboxes[1]=txtDetails.getText();
           
              
            
             
                     //Call the update method
                   PlnOp.update_plans(Integer.valueOf(txtID.getText()), textboxes);  
           
            
          
           
           } catch (SQLException ex) {JOptionPane.showMessageDialog(null,ex);   
        }
      
      }//End of update method 
      
      
      //Method to update the data 
       /**
        * 
        */
       public void update_frame() 
      {
      try { 
             //When we update first we check if the result set to updated is either search or show data
              
              if("".equals(txtSearch.getText()))
                 { 
                      set_update();
                    pln_RS=PlnOp.show_plans();
                //Call the method regresh to show the new updates in the form instantly
                     
                      show_data( idbo.refresh_data(pln_RS,index)  );
                     
                }
              else
              {      
                    set_update();
                   
                   pln_RS= PlnOp.search_plans(txtSearch.getText());
                    //Call the method regresh to show the new updates in the form instantly
                      show_data( idbo.refresh_data(pln_RS,index)  );
                 
              }
                             

        } catch (SQLException ex) { 
          
        }
      
      
      }//End of update data method
      
     
      
      
      //Method to delete a specific row in a record
      private void delete_row() throws SQLException, FileNotFoundException, IOException
      { 
         
         //Call the method designated for deleting rows 
               PlnOp.delete_plans(Integer.valueOf(txtID.getText()));
           //then jump to the nearest row     
              pln_RS=PlnOp.show_plans();
               index=Integer.valueOf(idbo.show_total(pln_RS));
               lblTotal1.setText(String.valueOf(index));
                   if(pln_RS.next())
                show_data(idbo.RS_next(pln_RS));
               else
                { index=1;
                   show_data(idbo.RS_first(pln_RS));
               }
      
      
      }  //End of delete row method
    
    
    
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtplan = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPosition1 = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plans");
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDetails.setBackground(new java.awt.Color(238, 238, 255));
        txtDetails.setBorder(null);
        jScrollPane2.setViewportView(txtDetails);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 220, 240));

        txtplan.setBackground(new java.awt.Color(255, 0, 0));
        txtplan.setBorder(null);
        jScrollPane3.setViewportView(txtplan);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 120, 60));

        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Title :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 20));

        jLabel2.setText("Details :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, 20));

        txtID.setEditable(false);
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("ID :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        btnDelete.setToolTipText("Delete this row");
        btnDelete.setBorder(null);
        btnDelete.setContentAreaFilled(false);
        btnDelete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Delete.jpg"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 3, 20, 20));

        btnUpdate.setToolTipText("update this row");
        btnUpdate.setBorder(null);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setInheritsPopupMenu(true);
        btnUpdate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Save 1.jpg"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 3, 20, 20));

        btnInsert.setToolTipText("Add new row");
        btnInsert.setBorder(null);
        btnInsert.setContentAreaFilled(false);
        btnInsert.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/new.jpg"))); // NOI18N
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 3, 20, 20));

        btnLast.setToolTipText("Move lats");
        btnLast.setBorder(null);
        btnLast.setBorderPainted(false);
        btnLast.setContentAreaFilled(false);
        btnLast.setRequestFocusEnabled(false);
        btnLast.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Last.jpg"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 3, 20, 20));

        btnNext.setToolTipText("Move next");
        btnNext.setBorder(null);
        btnNext.setContentAreaFilled(false);
        btnNext.setPreferredSize(new java.awt.Dimension(39, 23));
        btnNext.setRequestFocusEnabled(false);
        btnNext.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/next.jpg"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 3, 15, 20));

        jLabel13.setText("}");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 10, 20));

        lblTotal1.setToolTipText("Total rows");
        getContentPane().add(lblTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 3, 40, 20));

        jLabel11.setText("of {");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 3, 20, 20));

        lblPosition1.setToolTipText("Current position");
        getContentPane().add(lblPosition1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 3, 30, 20));

        btnPrevious.setToolTipText("Move previous");
        btnPrevious.setBorder(null);
        btnPrevious.setContentAreaFilled(false);
        btnPrevious.setPreferredSize(new java.awt.Dimension(39, 23));
        btnPrevious.setRequestFocusEnabled(false);
        btnPrevious.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Previous.jpg"))); // NOI18N
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 3, 15, 20));

        btnFirst.setBackground(new java.awt.Color(204, 255, 51));
        btnFirst.setToolTipText("Move first");
        btnFirst.setBorder(null);
        btnFirst.setContentAreaFilled(false);
        btnFirst.setPreferredSize(new java.awt.Dimension(39, 23));
        btnFirst.setRequestFocusEnabled(false);
        btnFirst.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/First.jpg"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        getContentPane().add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 20, 20));

        txtSearch.setToolTipText("Search for an ID or a text");
        txtSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 4, 167, 20));

        jButton3.setToolTipText("Exit");
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/x1.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 5, 20, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Searchicon_1.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 20, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("[Plans]");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 4, 50, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/bar2.jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 644, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/planss2.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed


        try {
            index = 1;
            //Call update data to save changes made in the row
            update_frame();
           
            //Show the data existing in the first item record
            show_data(idbo.RS_first(pln_RS));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }



    }//GEN-LAST:event_btnFirstActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

        try {
            //check if the search text is empty then show the all data
            if ("".equals(txtSearch.getText())) {
                index = 1;
               pln_RS = PlnOp.show_plans();
                lblTotal1.setText(idbo.show_total(pln_RS));

                show_data(idbo.RS_first(pln_RS));
                
            } else {
                //otherwise show the data according to the text enetered by the users
                index = 1;
               pln_RS = PlnOp.search_plans(txtSearch.getText());
                lblTotal1.setText(idbo.show_total(pln_RS));

                show_data(idbo.RS_first(pln_RS));
               
            }
        } catch (SQLException ex) {
           // Logger.getLogger(frmMainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        //Check if the row is not the first ,if it is then disable the user to delete it
        if (Integer.valueOf(txtID.getText()) == 1) {
            btnDelete.enable(false);
        } //if not then call the method delete row
        else {
            //Alert the users before deleting by poping up an option message
            int result = JOptionPane.showConfirmDialog(null, "Are you sure you wish to delete this row ?", "Alert", JOptionPane.YES_NO_CANCEL_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                try {
                    try {
                        delete_row();

                    } catch (FileNotFoundException ex) {
                      //  Logger.getLogger(frmMainPage.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                      //  Logger.getLogger(frmMainPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (SQLException ex) {
                }
            }

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //Call the method designated for update
        update_frame();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        //call the method designated for adding row
        try {
            add_new();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        //Call update data to save changes made in the row

        try {
            update_frame();

            index = Integer.valueOf(lblTotal1.getText());
            show_data(idbo.RS_last(pln_RS));




        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        //Set the index to the last item in the record
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed


        //Check if the index is not the last item 

        try {

            //Call update data to save changes made in the row
            update_frame();
            if (index < (Integer.valueOf(lblTotal1.getText()))) {   //if not then decrement the index to the next item in the record
                index++;
                //Show the data of the next record
                show_data(idbo.RS_next(pln_RS));

            }
            //show_image();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed

        try {
            //Call update data to save changes made in the row
            update_frame();


            if (index > 1) {
                //if not then decrement the index to the previous item in the record
                index--;
                show_data(idbo.RS_previous(pln_RS));

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_btnPreviousActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPlans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPlans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPlans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPlans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                try {
                    new frmPlans().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmPlans.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPosition1;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JTextPane txtDetails;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextPane txtplan;
    // End of variables declaration//GEN-END:variables
}
